language: cpp

compiler:  
    - gcc
     
git:
  depth: 1
  
install:
    - mkdir _Build
    - cd _Build
    - tar xf ../Tools/Linux/lcov_1.11.orig.tar.gz
    - sudo make -C lcov-1.11/ install
    - gem install coveralls-lcov
    - lcov --version
    
before_script: 
    - git clone --depth 1 https://${GITHUB_ACCESS_TOKEN}:x-oauth-basic@github.com/alewisw/aq.git --branch gh-pages --single-branch gh-pages
    - cd gh-pages
    - git config user.email "alewis.sw@gmail.com"
    - git config user.name "Travis CI"
    - cd ..
    - mkdir Debug
    - cd Debug
    - cmake ../.. -DCMAKE_BUILD_TYPE=DEBUG
    - cd ..
    - mkdir Release
    - cd Release
    - cmake ../.. -DCMAKE_BUILD_TYPE=RELEASE
    - cd ..
    - mkdir Performance
    - cd Performance
    - cmake ../.. -DCMAKE_BUILD_TYPE=PERFORMANCE
    - cd ..

script: 
    - cd Debug
    - make  
    - cd ..
    - cd Release
    - make  
    - cd ..
    - cd Performance
    - make  
    - cd ..
    - cd Debug
    - lcov --rc lcov_branch_coverage=1 --directory . --zerocounters
    - ./UnitTest/UnitTest
    - lcov --rc lcov_branch_coverage=1 --directory . --capture --output-file coverage.info
    - lcov --rc lcov_branch_coverage=1 --remove coverage.info '/usr/*' 'TestLib/*' 'UnitTest/*' 'TraceBuffer.cpp' 'TraceBuffer.h' 'TraceManager.cpp' 'TraceManager.h' 'TestPointNotifier.cpp' 'TestPointNotifier.h' --output-file aq-coverage.info
    - lcov --rc lcov_branch_coverage=1 --list aq-coverage.info
    - coveralls-lcov --repo-token ${COVERALLS_REPO_TOKEN} aq-coverage.info
    - mkdir ../lcov-genhtml
    - genhtml --rc lcov_branch_coverage=1 --output-directory ../lcov-genhtml --title "AQ Unit Test Code Coverage" --num-spaces 4 aq-coverage.info
    - cd ../gh-pages
    - git pull origin gh-pages
    - cp -fr ../lcov-genhtml/* .
    - git add *
    - git commit -a -m "Updated code coverage results"
    - git push origin gh-pages
